/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WiderrufRouteImport } from './routes/widerruf'
import { Route as WarenkorbRouteImport } from './routes/warenkorb'
import { Route as VersandZahlungRouteImport } from './routes/versand-zahlung'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as SetsRouteImport } from './routes/sets'
import { Route as ProdukteRouteImport } from './routes/produkte'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KollektionenRouteImport } from './routes/kollektionen'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DiscoveryBoxRouteImport } from './routes/discovery-box'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukteSlugRouteImport } from './routes/produkte.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedKontoRouteImport } from './routes/_authenticated/konto'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WiderrufRoute = WiderrufRouteImport.update({
  id: '/widerruf',
  path: '/widerruf',
  getParentRoute: () => rootRouteImport,
} as any)
const WarenkorbRoute = WarenkorbRouteImport.update({
  id: '/warenkorb',
  path: '/warenkorb',
  getParentRoute: () => rootRouteImport,
} as any)
const VersandZahlungRoute = VersandZahlungRouteImport.update({
  id: '/versand-zahlung',
  path: '/versand-zahlung',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsRoute = SetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukteRoute = ProdukteRouteImport.update({
  id: '/produkte',
  path: '/produkte',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KollektionenRoute = KollektionenRouteImport.update({
  id: '/kollektionen',
  path: '/kollektionen',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryBoxRoute = DiscoveryBoxRouteImport.update({
  id: '/discovery-box',
  path: '/discovery-box',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukteSlugRoute = ProdukteSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdukteRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthenticatedKontoRoute = AuthenticatedKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/discovery-box': typeof DiscoveryBoxRoute
  '/impressum': typeof ImpressumRoute
  '/kollektionen': typeof KollektionenRoute
  '/kontakt': typeof KontaktRoute
  '/produkte': typeof ProdukteRouteWithChildren
  '/sets': typeof SetsRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/versand-zahlung': typeof VersandZahlungRoute
  '/warenkorb': typeof WarenkorbRoute
  '/widerruf': typeof WiderrufRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/produkte/$slug': typeof ProdukteSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/discovery-box': typeof DiscoveryBoxRoute
  '/impressum': typeof ImpressumRoute
  '/kollektionen': typeof KollektionenRoute
  '/kontakt': typeof KontaktRoute
  '/produkte': typeof ProdukteRouteWithChildren
  '/sets': typeof SetsRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/versand-zahlung': typeof VersandZahlungRoute
  '/warenkorb': typeof WarenkorbRoute
  '/widerruf': typeof WiderrufRoute
  '/konto': typeof AuthenticatedKontoRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/produkte/$slug': typeof ProdukteSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agb': typeof AgbRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/discovery-box': typeof DiscoveryBoxRoute
  '/impressum': typeof ImpressumRoute
  '/kollektionen': typeof KollektionenRoute
  '/kontakt': typeof KontaktRoute
  '/produkte': typeof ProdukteRouteWithChildren
  '/sets': typeof SetsRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/versand-zahlung': typeof VersandZahlungRoute
  '/warenkorb': typeof WarenkorbRoute
  '/widerruf': typeof WiderrufRoute
  '/_authenticated/konto': typeof AuthenticatedKontoRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/produkte/$slug': typeof ProdukteSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/auth'
    | '/checkout'
    | '/datenschutz'
    | '/discovery-box'
    | '/impressum'
    | '/kollektionen'
    | '/kontakt'
    | '/produkte'
    | '/sets'
    | '/ueber-uns'
    | '/versand-zahlung'
    | '/warenkorb'
    | '/widerruf'
    | '/konto'
    | '/checkout/return'
    | '/produkte/$slug'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/auth'
    | '/checkout'
    | '/datenschutz'
    | '/discovery-box'
    | '/impressum'
    | '/kollektionen'
    | '/kontakt'
    | '/produkte'
    | '/sets'
    | '/ueber-uns'
    | '/versand-zahlung'
    | '/warenkorb'
    | '/widerruf'
    | '/konto'
    | '/checkout/return'
    | '/produkte/$slug'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agb'
    | '/auth'
    | '/checkout'
    | '/datenschutz'
    | '/discovery-box'
    | '/impressum'
    | '/kollektionen'
    | '/kontakt'
    | '/produkte'
    | '/sets'
    | '/ueber-uns'
    | '/versand-zahlung'
    | '/warenkorb'
    | '/widerruf'
    | '/_authenticated/konto'
    | '/checkout/return'
    | '/produkte/$slug'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgbRoute: typeof AgbRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  DatenschutzRoute: typeof DatenschutzRoute
  DiscoveryBoxRoute: typeof DiscoveryBoxRoute
  ImpressumRoute: typeof ImpressumRoute
  KollektionenRoute: typeof KollektionenRoute
  KontaktRoute: typeof KontaktRoute
  ProdukteRoute: typeof ProdukteRouteWithChildren
  SetsRoute: typeof SetsRoute
  UeberUnsRoute: typeof UeberUnsRoute
  VersandZahlungRoute: typeof VersandZahlungRoute
  WarenkorbRoute: typeof WarenkorbRoute
  WiderrufRoute: typeof WiderrufRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widerruf': {
      id: '/widerruf'
      path: '/widerruf'
      fullPath: '/widerruf'
      preLoaderRoute: typeof WiderrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warenkorb': {
      id: '/warenkorb'
      path: '/warenkorb'
      fullPath: '/warenkorb'
      preLoaderRoute: typeof WarenkorbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versand-zahlung': {
      id: '/versand-zahlung'
      path: '/versand-zahlung'
      fullPath: '/versand-zahlung'
      preLoaderRoute: typeof VersandZahlungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets': {
      id: '/sets'
      path: '/sets'
      fullPath: '/sets'
      preLoaderRoute: typeof SetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkte': {
      id: '/produkte'
      path: '/produkte'
      fullPath: '/produkte'
      preLoaderRoute: typeof ProdukteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kollektionen': {
      id: '/kollektionen'
      path: '/kollektionen'
      fullPath: '/kollektionen'
      preLoaderRoute: typeof KollektionenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery-box': {
      id: '/discovery-box'
      path: '/discovery-box'
      fullPath: '/discovery-box'
      preLoaderRoute: typeof DiscoveryBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkte/$slug': {
      id: '/produkte/$slug'
      path: '/$slug'
      fullPath: '/produkte/$slug'
      preLoaderRoute: typeof ProdukteSlugRouteImport
      parentRoute: typeof ProdukteRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/_authenticated/konto': {
      id: '/_authenticated/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof AuthenticatedKontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedKontoRoute: typeof AuthenticatedKontoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedKontoRoute: AuthenticatedKontoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ProdukteRouteChildren {
  ProdukteSlugRoute: typeof ProdukteSlugRoute
}

const ProdukteRouteChildren: ProdukteRouteChildren = {
  ProdukteSlugRoute: ProdukteSlugRoute,
}

const ProdukteRouteWithChildren = ProdukteRoute._addFileChildren(
  ProdukteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgbRoute: AgbRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  DatenschutzRoute: DatenschutzRoute,
  DiscoveryBoxRoute: DiscoveryBoxRoute,
  ImpressumRoute: ImpressumRoute,
  KollektionenRoute: KollektionenRoute,
  KontaktRoute: KontaktRoute,
  ProdukteRoute: ProdukteRouteWithChildren,
  SetsRoute: SetsRoute,
  UeberUnsRoute: UeberUnsRoute,
  VersandZahlungRoute: VersandZahlungRoute,
  WarenkorbRoute: WarenkorbRoute,
  WiderrufRoute: WiderrufRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
